server:
  http_listen_port: 3200
  grpc_server_max_recv_msg_size: 4194304  # 4MB
  grpc_server_max_send_msg_size: 4194304  # 4MB

distributor:
  receivers:
    otlp:
      protocols:
        grpc: 
          endpoint: "0.0.0.0:4317"  # Explicit binding
        http: {}

query_frontend:
  search:
    concurrent_jobs: 20
    max_duration: 30m


storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal