server:
  http_listen_port: 3200
  grpc_listen_port: 4317  # Explicitly set gRPC port

distributor:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal