server:
  http_listen_port: 3200
  grpc_server_max_recv_msg_size: 4194304  # 4MB
  grpc_server_max_send_msg_size: 4194304  # 4MB

distributor:
  receivers:
    otlp:
      protocols:
        grpc: 
          endpoint: "0.0.0.0:4317"  # Explicit binding
        http: {}


querier:
  frontend_worker:
    frontend_address: "tempo:9095"

query_frontend:
  search:
    concurrent_jobs: 10

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo