server:
  http_listen_port: 3200
  grpc_server_max_recv_msg_size: 4194304  # 4MB
  grpc_server_max_send_msg_size: 4194304  # 4MB

distributor:
  receivers:
    otlp:
      protocols:
        grpc: 
          endpoint: "0.0.0.0:4317"  # Explicit binding
        http: {}

querier:
  frontend_worker:
    frontend_address: "tempo-query-frontend:9095"  # Only this line is needed


storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal