server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc: 
          endpoint: "0.0.0.0:4317"  # Explicit binding
        http: {}


querier:
  frontend_worker:
    frontend_address: "tempo-query-frontend:9095"
    parallelism: 2

query_frontend:
  search:
    concurrent_jobs: 5

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo  # All files will be created under this directory